# Permalinks
permalink:           pretty

# Setup
title:               The Gospel
tagline:             in six
url:                 http://gospelinsix.com
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Cross City Church
  url:               http://crosscitychurch.org/
  email:             scott@crosscitychurch.org

# Custom vars
version:             2.0.0
github:
  repo:              

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
